### ISSUE TITLE
Dividers not show

### ISSUE THREAD

**Issue by Mioni** [asportnoy/role-dividers#3]
- Especiais
- Facção
- Registro
![image](https://user-images.githubusercontent.com/6830783/183305468-7c16b56c-0eda-45ff-8d7b-22ce23a6adf1.png)

**Comment by asportnoy** [comment]
Can you paste the name of the roles here?

**Comment by Mioni** [comment]
> Can you paste the name of the roles here?

⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀・ESPECIAIS

⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀・FACÇÃO⠀

⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀・REGISTRO

It's in portuguese-br roles, must that be why it doesn't work?

**Comment by asportnoy** [comment]
Should be fixed in the latest version (1.0.10), please update and confirm. I added an additional character (`・`) to the list and allowed for no spaces at the end of the role.

**Comment by Mioni** [comment]
Works! Thank you!
